name: menu
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  fluro: "^1.3.1"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
      - assets/images/menu1.png
      - assets/images/menu2.png
      - assets/images/menu3.png
      - assets/images/menu4.png
      - assets/images/menu5.png
      - assets/images/menu7.png
      - assets/images/menu8.png
      - assets/images/menu9.png
      - assets/images/menu10.png
      - assets/images/menu11.png
      - assets/images/menu12.png
      - assets/images/menu13.png
      - assets/images/menu14.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
     - family: fontello
       fonts:
         - asset: assets/fonts/fontello.ttf
     - family: Dosis
       fonts:
         - asset: assets/fonts/Dosis/Dosis-Regular.ttf
           weight: 400
         - asset: assets/fonts/Dosis/Dosis-Medium.ttf
           weight: 500
         - asset: assets/fonts/Dosis/Dosis-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Dosis/Dosis-Bold.ttf
           weight: 800
         - asset: assets/fonts/Dosis/Dosis-ExtraBold.ttf
           weight: 900
